# Generated by Django 5.2.11 on 2026-02-28 16:10

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluencePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('space', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('version', models.IntegerField(default=1)),
                ('page_created_date', models.DateTimeField(blank=True, null=True)),
                ('page_updated_date', models.DateTimeField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'confluence_pages',
                'ordering': ['-page_updated_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateField()),
                ('rationale', models.TextField(blank=True, null=True)),
                ('alternatives_considered', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('decided_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('source_type', models.CharField(choices=[('meeting', 'Meeting'), ('confluence', 'Confluence'), ('jira', 'Jira'), ('git_commit', 'Git Commit')], max_length=50)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('source_title', models.CharField(blank=True, max_length=500, null=True)),
                ('related_tickets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('related_decisions', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('category', models.CharField(blank=True, choices=[('architecture', 'Architecture'), ('technology', 'Technology'), ('process', 'Process'), ('design', 'Design'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('other', 'Other')], max_length=100, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('reversed', 'Reversed'), ('proposed', 'Proposed'), ('duplicate', 'Duplicate')], default='active', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extraction_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-decision_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('github_username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntityReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('commit', 'Git Commit'), ('meeting', 'Meeting'), ('jira_ticket', 'Jira Ticket'), ('confluence', 'Confluence Page')], max_length=50)),
                ('source_id', models.UUIDField()),
                ('reference_type', models.CharField(choices=[('jira_ticket', 'Jira Ticket'), ('commit', 'Git Commit')], max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('extraction_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entity_references',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=255)),
                ('commit_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('related_tickets', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'git_commits',
                'ordering': ['-commit_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GitCommitFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'git_commit_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_key', models.CharField(max_length=50, unique=True)),
                ('issue_type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('labels', models.TextField(blank=True, null=True)),
                ('epic_link', models.CharField(blank=True, max_length=50, null=True)),
                ('sprint', models.CharField(blank=True, max_length=100, null=True)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jira_tickets',
                'ordering': ['-created_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('raw_vtt_content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('key_decisions', models.TextField(blank=True, null=True)),
                ('action_items', models.TextField(blank=True, null=True)),
                ('participants', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-meeting_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('epic_key', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_project_key', models.CharField(blank=True, max_length=20, null=True)),
                ('github_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('confluence_space_key', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('team_members', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('commit', 'Git Commit'), ('meeting', 'Meeting'), ('jira_ticket', 'Jira Ticket'), ('confluence', 'Confluence Page')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('added_manually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_entities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprint_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('goal', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sprints',
                'ordering': ['sprint_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SprintTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sprint_tickets',
                'managed': False,
            },
        ),
    ]
