# Generated by Django 5.2.11 on 2026-05-09 22:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("indirect", "Indirect"),
                            ("potential", "Potential"),
                        ],
                        max_length=50,
                    ),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "decision_conflicts",
                "managed": False,
            },
        ),
    ]
